package xyz.heurlin.poketouch.emulator

object Charmap {
    private val charMap = mapOf<Byte, String>(
        0x50.toByte() to "@", // string terminator
        0x80.toByte() to "A",
        0x81.toByte() to "B",
        0x82.toByte() to "C",
        0x83.toByte() to "D",
        0x84.toByte() to "E",
        0x85.toByte() to "F",
        0x86.toByte() to "G",
        0x87.toByte() to "H",
        0x88.toByte() to "I",
        0x89.toByte() to "J",
        0x8a.toByte() to "K",
        0x8b.toByte() to "L",
        0x8c.toByte() to "M",
        0x8d.toByte() to "N",
        0x8e.toByte() to "O",
        0x8f.toByte() to "P",
        0x90.toByte() to "Q",
        0x91.toByte() to "R",
        0x92.toByte() to "S",
        0x93.toByte() to "T",
        0x94.toByte() to "U",
        0x95.toByte() to "V",
        0x96.toByte() to "W",
        0x97.toByte() to "X",
        0x98.toByte() to "Y",
        0x99.toByte() to "Z",

        0x9a.toByte() to "(",
        0x9b.toByte() to ")",
        0x9c.toByte() to ":",
        0x9d.toByte() to ";",
        0x9e.toByte() to "[",
        0x9f.toByte() to "]",

        0xa0.toByte() to "a",
        0xa1.toByte() to "b",
        0xa2.toByte() to "c",
        0xa3.toByte() to "d",
        0xa4.toByte() to "e",
        0xa5.toByte() to "f",
        0xa6.toByte() to "g",
        0xa7.toByte() to "h",
        0xa8.toByte() to "i",
        0xa9.toByte() to "j",
        0xaa.toByte() to "k",
        0xab.toByte() to "l",
        0xac.toByte() to "m",
        0xad.toByte() to "n",
        0xae.toByte() to "o",
        0xaf.toByte() to "p",
        0xb0.toByte() to "q",
        0xb1.toByte() to "r",
        0xb2.toByte() to "s",
        0xb3.toByte() to "t",
        0xb4.toByte() to "u",
        0xb5.toByte() to "v",
        0xb6.toByte() to "w",
        0xb7.toByte() to "x",
        0xb8.toByte() to "y",
        0xb9.toByte() to "z",

        0xc0.toByte() to "Ä",
        0xc1.toByte() to "Ö",
        0xc2.toByte() to "Ü",
        0xc3.toByte() to "ä",
        0xc4.toByte() to "ö",
        0xc5.toByte() to "ü",

        0xd0.toByte() to "'d",
        0xd1.toByte() to "'l",
        0xd2.toByte() to "'m",
        0xd3.toByte() to "'r",
        0xd4.toByte() to "'s",
        0xd5.toByte() to "'t",
        0xd6.toByte() to "'v",

        0xdf.toByte() to "←",
        0xe0.toByte() to "'",
        0xe1.toByte() to "<PK>",
        0xe2.toByte() to "<MN>",
        0xe3.toByte() to "-",

        0xe6.toByte() to "?",
        0xe7.toByte() to "!",
        0xe8.toByte() to ".",
        0xe9.toByte() to "&",

        0xea.toByte() to "é",
        0xeb.toByte() to "→",
        0xec.toByte() to "▷",
        0xed.toByte() to "▶",
        0xee.toByte() to "▼",
        0xef.toByte() to "♂",
        0xf0.toByte() to "¥",
        0xf1.toByte() to "×",
        0xf2.toByte() to "<DOT>",
        0xf3.toByte() to "/",
        0xf4.toByte() to ",",
        0xf5.toByte() to "♀",

        0xf6.toByte() to "0",
        0xf7.toByte() to "1",
        0xf8.toByte() to "2",
        0xf9.toByte() to "3",
        0xfa.toByte() to "4",
        0xfb.toByte() to "5",
        0xfc.toByte() to "6",
        0xfd.toByte() to "7",
        0xfe.toByte() to "8",
        0xff.toByte() to "9",
    )

    public fun bytesToString(byteArray: ByteArray): String {
        return byteArray.joinToString("") {
            charMap.getOrDefault(it, "?")
        }
    }
}
